CREATE TABLE IF NOT EXISTS users (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  discord_user_id VARCHAR(64) NOT NULL UNIQUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS gmail_accounts (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT UNSIGNED NOT NULL,
  google_sub VARCHAR(255) NOT NULL,
  email VARCHAR(320) NOT NULL,
  access_token TEXT NOT NULL,
  refresh_token TEXT NULL,
  expiry_date BIGINT NULL,
  scopes TEXT NOT NULL,
  reauth_required TINYINT(1) NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_gmail_user_email (user_id, email),
  CONSTRAINT fk_gmail_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS settings (
  user_id BIGINT UNSIGNED NOT NULL PRIMARY KEY,
  summary_time CHAR(5) NOT NULL DEFAULT '09:00',
  timezone VARCHAR(100) NOT NULL DEFAULT 'UTC',
  ai_provider VARCHAR(32) NOT NULL DEFAULT 'openai',
  ai_model VARCHAR(120) NOT NULL DEFAULT 'gpt-4o-mini',
  ai_api_key TEXT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_settings_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS feedback (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT UNSIGNED NOT NULL,
  message_id VARCHAR(128) NULL,
  rating ENUM('helpful','not_helpful') NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_feedback_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS summary_history (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT UNSIGNED NOT NULL,
  local_date DATE NOT NULL,
  delivery_kind ENUM('scheduled','manual') NOT NULL,
  status ENUM('processing','complete','failed') NOT NULL,
  summary_text TEXT NULL,
  error_code VARCHAR(64) NULL,
  claimed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  completed_at TIMESTAMP NULL,
  delivery_attempted TINYINT(1) NOT NULL DEFAULT 0,
  attempt_count INT NOT NULL DEFAULT 0,
  UNIQUE KEY uq_summary_claim (user_id, local_date, delivery_kind),
  CONSTRAINT fk_history_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;
