const checks = [
  ["Read-only scope", "MailDM requests Gmail `gmail.readonly` only. It does not compose, send, archive, label, delete, or mark messages as read.", "Ready"],
  ["Private testing", "Named Gmail test users can connect while the Google OAuth project remains in testing status.", "In progress"],
  ["Public identity", "Before public access, MailDM will publish a stable homepage, support contact, privacy policy, and terms on an operator-owned domain.", "Planned"],
  ["Restricted-scope review", "The operator will document the Gmail data flow, submit a consent-flow demo, justify the minimum scope, and complete Google’s required review process before broad release.", "Planned"],
];

export default function GmailReadiness() {
  return <div className="min-h-screen bg-[#f5f1e9] px-5 py-5 text-[#1e2926] sm:px-8 lg:px-12"><main className="mx-auto max-w-3xl"><header className="flex items-center justify-between border-b border-[#1e2926]/15 pb-5"><a className="flex items-center gap-3" href="/"><span className="grid h-9 w-9 place-items-center rounded-full bg-[#1e2926] font-['Playfair_Display'] text-xl text-[#f7f4ed]">M</span><span className="text-sm font-extrabold tracking-[-0.03em]">MailDM</span></a><span className="font-['DM_Mono'] text-[10px] uppercase tracking-[0.16em] text-[#68776f]">Gmail readiness</span></header><article className="py-16 sm:py-20"><p className="font-['DM_Mono'] text-[10px] uppercase tracking-[0.18em] text-[#6d8f7f]">OAuth transparency</p><h1 className="mt-5 font-['Playfair_Display'] text-5xl leading-[0.95] tracking-[-0.06em] sm:text-6xl">Gmail access, carefully prepared.</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-[#53635d]">MailDM starts with named-user testing. Broad Gmail availability comes only after the app’s public identity, privacy disclosures, and Google OAuth verification work are complete.</p><div className="mt-12 divide-y divide-[#1e2926]/15 border-y border-[#1e2926]/15">{checks.map(([title, detail, status]) => <section className="grid gap-3 py-6 sm:grid-cols-[1fr_auto]" key={title}><div><h2 className="text-xl font-extrabold tracking-[-0.035em]">{title}</h2><p className="mt-2 max-w-xl leading-7 text-[#53635d]">{detail}</p></div><span className="self-start rounded-full border border-[#6d8f7f]/35 bg-[#dce6d7]/60 px-3 py-1 font-['DM_Mono'] text-[10px] uppercase tracking-[0.12em] text-[#4f6d5d]">{status}</span></section>)}</div><div className="mt-10 rounded-2xl bg-[#20312c] p-7 text-[#f6f1e7]"><p className="font-['DM_Mono'] text-[10px] uppercase tracking-[0.16em] text-[#b7c8bd]">Your control</p><p className="mt-3 text-lg font-bold">You can disconnect an account or delete all MailDM data from a private Discord conversation at any time.</p><a className="mt-5 inline-block font-['DM_Mono'] text-[10px] uppercase tracking-[0.14em] text-[#b7c8bd] underline underline-offset-4 hover:text-white" href="/privacy">Read the privacy policy</a></div></article><footer className="flex gap-5 border-t border-[#1e2926]/15 py-7 font-['DM_Mono'] text-[10px] uppercase tracking-[0.13em] text-[#78867e]"><a className="hover:text-[#1e2926]" href="/">Home</a><a className="hover:text-[#1e2926]" href="/privacy">Privacy</a><a className="hover:text-[#1e2926]" href="/terms">Terms</a></footer></main></div>;
}
