const sections = [
  ["What MailDM accesses", "After you choose to connect an account, MailDM requests Gmail read-only access. During a digest, it reads unread-message metadata and limited body text only to create your requested brief. It does not send, delete, archive, label, or mark messages as read."],
  ["How Gmail data is used", "MailDM normalizes and sanitizes fetched unread messages in memory, then sends the bounded, normalized content to the AI provider and model you selected in order to create your brief. Email content is not retained after processing. MailDM does not use Gmail data for advertising, selling, or training its own models."],
  ["What MailDM stores", "MailDM stores your Discord identifier, connected-account label and address, schedule preferences, safe delivery history, message identifiers for deduplication, and encrypted Gmail refresh tokens and AI keys. It does not store your Gmail password or raw email bodies."],
  ["Sharing and protection", "MailDM sends summary input only to the AI provider you actively configure. Credentials are encrypted at rest and are never shown in the MailDM website, Discord replies, audit records, or logs. The application uses Gmail read-only OAuth access and verified Discord interactions."],
  ["Retention and deletion", "You can run /disconnect <account_id> in a direct message with MailDM to revoke and permanently remove a Gmail connection and its stored encrypted token. Run /delete-my-data with confirm set to DELETE to remove your MailDM account, encrypted AI keys, Gmail connections, schedules, preferences, and summary history. Safe, de-identified audit events may remain where technically necessary for security records."],
  ["Contact and changes", "For account support or a data request, send a direct message to MailDM and use the available account commands. Before MailDM is opened beyond named test users, the operator will publish a verified-domain support contact and update this policy if data practices change."],
];

export default function Privacy() {
  return <div className="min-h-screen bg-[#f5f1e9] px-5 py-5 text-[#1e2926] sm:px-8 lg:px-12"><main className="mx-auto max-w-3xl"><header className="flex items-center justify-between border-b border-[#1e2926]/15 pb-5"><a className="flex items-center gap-3" href="/"><span className="grid h-9 w-9 place-items-center rounded-full bg-[#1e2926] font-['Playfair_Display'] text-xl text-[#f7f4ed]">M</span><span className="text-sm font-extrabold tracking-[-0.03em]">MailDM</span></a><span className="font-['DM_Mono'] text-[10px] uppercase tracking-[0.16em] text-[#68776f]">Privacy notice</span></header><article className="py-16 sm:py-20"><p className="font-['DM_Mono'] text-[10px] uppercase tracking-[0.18em] text-[#6d8f7f]">Gmail-first · read only</p><h1 className="mt-5 font-['Playfair_Display'] text-5xl leading-[0.95] tracking-[-0.06em] sm:text-6xl">Privacy, stated plainly.</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-[#53635d]">MailDM is built to make your unread inbox more useful without changing it. This policy explains how Gmail information is handled when you choose to connect an account.</p><div className="mt-12 space-y-8">{sections.map(([title, content]) => <section className="border-t border-[#1e2926]/15 pt-6" key={title}><h2 className="text-xl font-extrabold tracking-[-0.035em]">{title}</h2><p className="mt-3 max-w-2xl leading-7 text-[#53635d]">{content}</p></section>)}</div><p className="mt-12 font-['DM_Mono'] text-[10px] uppercase tracking-[0.14em] text-[#78867e]">Last updated · August 2026</p></article><footer className="flex gap-5 border-t border-[#1e2926]/15 py-7 font-['DM_Mono'] text-[10px] uppercase tracking-[0.13em] text-[#78867e]"><a className="hover:text-[#1e2926]" href="/">Home</a><a className="hover:text-[#1e2926]" href="/terms">Terms</a><a className="hover:text-[#1e2926]" href="/status">Status</a></footer></main></div>;
}
